# Use an official PostgreSQL image as a parent image
FROM postgres:latest

# Set environment variables for PostgreSQL
ENV POSTGRES_USER budgy
ENV POSTGRES_PASSWORD your_password
ENV POSTGRES_DB budgy_production

# Expose the default PostgreSQL port
EXPOSE 5432
